### ISSUE TITLE
Kalatheme as admin theme not showing panel columns aside

### ISSUE THREAD

**Issue by parijke** [drupalprojects/kalatheme#104]
Hi all,

As recommended in the installation I enabled Kalatheme as the admin theme as well. This doesn't look very good in my opinion, but I also have the issue that the columns (like Burr) are shown on top of eachother in stead of next to eachother.

![image](https://cloud.githubusercontent.com/assets/7671998/3454868/98bbc978-01d7-11e4-9642-49e8307e8ff3.png)

**Comment by pirog** [comment]
I don't think you need to set as admin theme anymore. What version here?

**Comment by parijke** [comment]
Hi Mike,

Kalatheme 7.x-4.x-dev

**Comment by parijke** [comment]
I enabled Seven as the admin theme and that works fine

**Comment by pirog** [comment]
@katypool ... should update the docs to state that setting kalatheme as the admin theme is no longer required
