### ISSUE TITLE
Kalatheme 3.0 + views_bootstrap = weirdness

### ISSUE THREAD

**Issue by labboy0276** [drupalprojects/kalatheme#106]
OK

So I updated CSi's site to kalatheme 3.0 and updated their bootstrap library as well to 3.2.  For some reason the views_bootstrap carousel goes haywire now.  

What happens is, it runs through the first pass no problem, when it goes back around it seems like it loses count as to where it is in the queue.  So what is happening is, say there are 4 items in the carousel, it goes through the first 4 no problem, comes back, skips to the 2nd, tried to go to the 4th and it then begins to display multiple slides.

I tried this on their regular 3.1 whatever bootstrap custom library and an upgraded 3.2, same results

As soon as I revert back to kalatheme 3.0-rc2, all is well

Not sure what is up here

**Comment by pirog** [comment]
Are we overriding the markup for the carousel in the new version? If so , what is different?

**Comment by labboy0276** [comment]
After investigating, this is more of a bootstrap 3.2 issue it seems

On a rc2 install + bootstrap = 3.2 this is happening, oy....

Odd thing though is that when it was just kalatheme 3.0 + bootstrap 3.1 = weirdness, so idk.  Waiting to see if @bassettsj knows if anything was changed in this area

**Comment by bassettsj** [comment]
Yeah, they changed some of their markup in the carousel. Let's dig into views_bootstrap and fix it. Shouldn't be hard.

**Comment by labboy0276** [comment]
Check this out, line 288 of the bootstrap.js

if (this.sliding)       return this.$element.one('slid.bs.carousel', function () { that.to(pos) }) // yes, "slid"

its a typo...

should be slide.bs, let me see if this wins it

**Comment by labboy0276** [comment]
actually it isnt, nevermind, the use slid and slide interchangeably

**Comment by pirog** [comment]
+1 on @bassettsj let's see if we can fix this on the views_bootstrap side
