### ISSUE TITLE
Best approach to work without a fixed header, replace it with a mini-panel?

### ISSUE THREAD

**Issue by maxplus** [drupalprojects/kalatheme#121]
Hi,
I like the way Kalatheme is build on Panopoly and very flexible is in its page layouts.
One optimalisation that I want to do the right way, is to also get rid of the default "static" header (including the Drupal standard theme settings like Site logo / main menu / secondary menu / ....)

The way I'm doing it right now is:
1. First I override the page.tpl.php that is provided by the base Kalatheme inside my own theme (in mytheme/templates/core folder).
   => In this page.tpl.php I get rid of the complete   part
2. Then I create a Mini Panel that contains my header elements, like Sitelogo / Main menu / ...
    => TODO: I have to add the navbar classes and stuff, so I also get the responsive collapsed Bootstrap mobile menu
3. Then I add this Mini Panel to every page where I need it, using the page manager.

Is this the right way to do it?

**Comment by pirog** [comment]
@maxplus i _think_ that if you disable all the elements in the header that kalatheme hides the entire header. 

from the documentation:
https://github.com/drupalprojects/kalatheme/wiki/Kalatheme-settings-and-config

> "This works essentially how you are used to it working on other Drupal themes. The logo, site name and slogan all appear on the upper left of the header while main and secondary menus appear on the upper right. **If you want to disable the display of the entire header and run a site completely with panels layouts (which would be hot by the way) you can do so by disabling logo, site name, slogan, main and secondary menus.** Also, please note that if you create your own page.tpl.php in your subtheme that these options may no longer work. I would use the page.tpl.php in Kalatheme for inspiration when crafting your own page template."

I think the way you are doing it is completely fine as well but if you didnt want to create a new page template you could just follow the suggestion above. 

Does that help at all?

**Comment by maxplus** [comment]
Yes,
I just wanted to check if I'm going in the right direction.
I understand that I also could use the default template and disable all the header elements inside the theme settings page.

Now I only need to get the mobile menu working like it should (I think by adding the navbar classes and stuff to the mini panel that replaces the static header).

Very powerfull!

**Comment by pirog** [comment]
Definitely sounds like the right direction to me! 
Going to close but feel free to reopen!

**Comment by maxplus** [comment]
Hi,
I like the approach of a complete One Region setup, run whole site on panels, so no hardcoded header.
There is one problem with this setup: your Drupal default stuff like : $messages, $tabs, $action_links => get on top of everything... and that is not so nice (because my subtheme is still using the core page.tpl where they are all printed at the top-content div:



  <div id="main-wrapper" class="clearfix">
    <main id="main" class="clearfix" role="main">
      <div id="top-content">
        <div class="column container">
          <a id="main-content"></a>
          <?php if (($no_panels || $always_show_page_title) && $title): ?>
            <h1 id="page-title" class="title">
              <?php print $title; ?>
            </h1>
          <?php endif; ?>

```
      <?php if ($messages): ?>
        <div id="messages">
          <?php print $messages; ?>
        </div>
      <?php endif; ?>

      <?php if (!empty($tabs['#primary']) || !empty($tabs['#secondary'])): ?>
        <div id="tabs">
          <?php print render($tabs); ?>
        </div>
      <?php endif; ?>

      <?php if ($action_links): ?>
        <div id="action-links">
          <?php print render($action_links); ?>
        </div>
      <?php endif; ?>
    </div>
  </div> <!-- /.section, /#top-content -->
```

Now I think I have to create custom panel layouts in my own theme folder, so I can position them inside every template correctly or add a custom region to them to always place them there.

Mmmm... so the full One Region setup is maybe not that handy at all. Like you said before, it may be better to just keep using a hard coded header and footer after all

**Comment by maxplus** [comment]
After thinking about my previous post, I maybe found some kind of nicer solution to have the best of both worlds:
1. create a mini panel for your header: this still gives your client all the edit modifications
2. render this mini panel inside your page.tpl
3. put the "$messages, $tabs, $action_links" below this mini panel
4. print de rest of your content

So in my case, my custom page.tpl looks like this:

<?php
/_printing the mini panel_/
$block = module_invoke('panels_mini', 'block_view', 'header');
print $block['content']; 

/_printing the messages, tabs and action links_/?>

<div class="container">
   <?php if ($messages): ?>
        <div id="messages">
              <?php print $messages; ?>
        </div>

   <?php endif; ?>
   <?php if (!empty($tabs['#primary']) || !empty($tabs['#secondary'])): ?>
        <div id="tabs">
             <?php print render($tabs); ?>
        </div>
   <?php endif; ?>
   <?php if ($action_links): ?>
         <div id="action-links">
              <?php print render($action_links); ?>
         </div>
   <?php endif; ?>
</div> 

<?php 
/_render the rest of the page based on panels_/
print render($page['content']); ?>

**Comment by npoku** [comment]
@maxplus last post really helped me out. Loved the logic. Ended up injecting the header + footer via his method.  👏👏
