### ISSUE TITLE
views grouping leads to notice undefined offset in include()

### ISSUE THREAD

**Issue by enxox** [drupalprojects/kalatheme#124]
I have a view pane listing all nodes of a certain type, in a table, using fields.

Everything fine, untill I chose one field for grouping (from format table settings).

On the page the output is fine, but I have some notices of this type:

Notice: Undefined offset: # in include() (line 39 of /sites/all/modules/contrib/views/theme/views-view-table.tpl.php)
 (# is the number of the offset)

Actually the issue is on 7.3.x and 7.3.0

**Comment by pirog** [comment]
@labboy0276 seems like this shouldn't be too hard to fix. can you give it a look see?

**Comment by labboy0276** [comment]
@pirog I fixed it and added it to master as well, submiited PR

**Comment by pirog** [comment]
@enxox try this out on the latest dev and see if it resolves your issue. reopen if not!

**Comment by enxox** [comment]
it works!
thank you
