### ISSUE TITLE
CSS Menu Selectors by menu id not possible

### ISSUE THREAD

**Issue by break9** [drupalprojects/kalatheme#13]
The menu ID's are assigned to the "li"'s as a class and written to the browser as class = numeric ID. The problem is that you can't call a class that begins with a number.

the current html generated by the theme is "li class="1133"" you cannot reference the element by referencing .1133 or li.1133 in your css, it is invalid css.

other themes append the word "menu" to each of the ID's so that the resulting css is "li class="menu-1133-1"" which you can reference in your css as .menu-1133-1, and is valid css

**Comment by bassettsj** [comment]
Was fixed a while ago on the 7.x-4.x branch. Thanks for reporting.

**Comment by pirog** [comment]
Does this need to be back ported to 3.x?

**Comment by bassettsj** [comment]
Yeah. —
