### ISSUE TITLE
Modals stopped working in 3.0

### ISSUE THREAD

**Issue by labboy0276** [drupalprojects/kalatheme#132]
I upgraded a site to the latest kalatheme and poof all the modals stopped working.  I tried upgrading the bootstrap library to 3.2 and still no go.

I dont see any errors in the console, not sure why this has happened

**Comment by pirog** [comment]
Hmmm... i'm not convinced this is kalatheme. 
http://kalatheme.kalamuna.com/demo is running on the latest 3.x dev and latest Panopoly and modals seem fine. I would try to find out what the difference is between http://kalatheme.kalamuna.com/demo and your site.

What modals aren't working? can you be more specific? 

One thing that i did notice which we should open a new issue for is the "x" close character for IPE based modals needs to be set to a color so it is visible.

**Comment by jpstrikesback** [comment]
I've noticed this with an upgrade from panopoly 1.7 to 1.9, the media asset selection modal (upload, web, library) has a z-index of 2 or something and the panelizer modals have a z-index of 1000 or so...I wonder if an upgrade to the media module took place and there was a style change in it...

**Comment by labboy0276** [comment]
Well @jpstrikesback is correct I did upgrade to 1.9.  The modals are in a text widget within a panel.  When I revert back to rc2 they work, when I go to 3.0 they dont.  So that is what is going on without digging into the problem more quite yet.

**Comment by pirog** [comment]
@labboy0276 can post your text widget code for this? 

does this also happen when you are on the new panopoly 1.10?

**Comment by jpstrikesback** [comment]
This is nuts but it seems related to jquery update. I haven't checked what Panopoly was serving prior to the update but after it was serving 1.7 and the other options were 1.5 & 1.8 (old), updated Jquery Update to the latest release (7.x-2.4) which defaults to 1.10 and modals are working again.

**Comment by andrewmallis** [comment]
I have found that the latest latest jquery can break some other IPE functionality, so you should test thoroughly.

**Comment by pirog** [comment]
ugh... for real? 

DRUPALLLLLLLLLLL CMONNNNNNNN

**Comment by rokat** [comment]
If my memory serves, panopoly didn't update jquery to the latest version because the modal for Media is showing under CTools modal.
https://www.drupal.org/node/2245143
Maybe if we help them test it so that it may be fixed it could help us all.
Changing jquery version (set to use 1.8) version in 2.3 version is very buggy IPE breaks etc (wrong z-index).

**Comment by labboy0276** [comment]
OK @pirog 

So i updated to 1.10 panopoly, kalatheme 3.0 and it still doesnt work
I tried downgrading jquery_update to 2.3, still no work

I downgraded kalatheme to rc2 (with panopoly 1.10) and it works just fine

So the problem here it seems lies within something in kalatheme more then likely

The modal is within a panel widget here:  www.fiksu.com/fiksu-obstacle-course

It is a very large modal setup with many elements as you can see.

**Comment by pirog** [comment]
@labboy0276 got it... but can you share some of the actual HTML you are using to make this happen so i can test it out on a clean install? i still cant even replicate this yet.

**Comment by labboy0276** [comment]
@pirog Indeed here ya go:  https://gist.github.com/labboy0276/0c75b82380088dd2b2bc

**Comment by andrewmallis** [comment]
@labboy0276 that gist is broken. Is this issue still relevant or resolved in 7.x-3.1?

**Comment by labboy0276** [comment]
Negative
