### ISSUE TITLE
Drop-down menu caret placement

### ISSUE THREAD

**Issue by jpstrikesback** [drupalprojects/kalatheme#133]
See: https://www.drupal.org/node/2262301 and http://getbootstrap.com/javascript/#dropdowns-examples

The dropdown caret is placed in it's own `<a>` and should probably be inside the dropdown `<a>`.

**Comment by jpstrikesback** [comment]
PR is in #134

**Comment by pmackay** [comment]
This could have the effect that its not possible to click on an actual main menu item. The Drupal Bootstrap theme I think already does what this issue suggests, but it means the visible menu item is just a toggle for showing the dropdown menu (maybe there is something I'm missing). Kalatheme current behaviour allows the visible menu item to be clicked and also click the caret to see the dropdown.

**Comment by katypool-zz** [comment]
Think we can close this out as #134 is merged
