### ISSUE TITLE
Notice: Trying to get property of non-object in kalatheme_process_page() (line 122 of XXX/sites/all/themes/kalatheme/template.php).

### ISSUE THREAD

**Issue by carsonblack** [drupalprojects/kalatheme#14]
This notice is showing up on the settings page. This is before I have done anything other than enable and set as default.

**Comment by pirog** [comment]
I think there is some weirdness with libraries 2.2 and kalatheme. Does it go away if you roll back to 2.1?

**Comment by pirog** [comment]
This may also be relevant
https://drupal.org/node/2265741

**Comment by bassettsj** [comment]
Might be worthwhile to look into some error checking on the calls to libraries and th bootswatch API. I will look into a pull request soon

**Comment by EcoFin** [comment]
I continue to get the same error (Notice: Trying to get property of non-object in kalatheme_process_page() (line 122 of C:\wamp\www\panopoly-7.16\sites\all\themes\kalatheme\template.php). immediately after setting kalatheme as the default and clicking "save config". 

This is on a completely clean new install of panopoly 1.6 running on a local wamp development server under Win 8.1.  I already reported (on drupal site) that the same thing happens on a standard drupal setup that meets kalatheme's stated requirements.   Backing down to libraries 2.1 has absolutely no impact in either context.

There is no "setup" option available despite cache flushing.  Just choosing the available "settings" generates more errors as below:

*Notice: Trying to get property of non-object in kalatheme_process_page() (line 122 of C:\wamp\www\panopoly-7.16\sites\all\themes\kalatheme\template.php).
*Notice: Trying to get property of non-object in kalatheme_process_page() (line 122 of C:\wamp\www\panopoly-7.16\sites\all\themes\kalatheme\template.php).
*Warning: include_once(C:\wamp\www\panopoly-7.16/C:\wamp\www\panopoly-7.16\sites\all\themes\kalatheme\includes/../kalatheme.authorize.inc): failed to open stream: Invalid argument in _batch_finished() (line 461 of C:\wamp\www\panopoly-7.16\includes\batch.inc).
*Warning: include_once(): Failed opening 'C:\wamp\www\panopoly-7.16/C:\wamp\www\panopoly-7.16\sites\all\themes\kalatheme\includes/../kalatheme.authorize.inc' for inclusion (include_path='.;C:\php\pear') in _batch_finished() (line 461 ofC:\wamp\www\panopoly-7.16\includes\batch.inc).

Noting the "*Warning: include_once(C:\wamp\www\panopoly-7.16/C:\wamp\www\panopoly- ..." I wonder if it is constructing a string incorrectly.

**Comment by labboy0276** [comment]
After the commit I made for Issue#19 this will go away if you re-save the subtheme with the patch

it seems it is getting mixed up still in seeing that sites/all/libraries is there, i will look at the function in util.inc and see if a tweak can be made

**Comment by bassettsj** [comment]
Let's keep this issue open for sure. I want to make sure it gets fixed soon.

**Comment by labboy0276** [comment]
I am working on it now

**Comment by bassettsj** [comment]
You don't have to solve it but I love that you're working on it. Submit the pull request against drupalprojects/kalatheme, master branch.

**Comment by pirog** [comment]
I also love that you are! 

GO TEAM!

**Comment by labboy0276** [comment]
got it, putting in pull request

**Comment by labboy0276** [comment]
Hey Steven, seems you marked this fixed in #43, can you close out this issue then as it seems resolved
