### ISSUE TITLE
Mobile view hamburger button will not hide menu

### ISSUE THREAD

**Issue by hexosecs** [drupalprojects/kalatheme#140]
When clicking on the hamburger it shows the menu fine but on clicking it again the menu disappears and then reappears.

This is on the latest kalatheme downloaded today for drupal 7.

Please ask if you need any further information.

**Comment by mrausch** [comment]
I was affected by the same issue, using jQuery Update set to jQuery version 1.7 as recommended (and using a custom Bootstrap 3.2 library).
After I changed jQuery version to 1.10 on the jQuery-Update settings page, the issue disappeared, i.e. the collapse button for the navigation works as intended again. Beware though: this might introduce other issues which I cannot foresee right now.

**Comment by labboy0276** [comment]
It seems to be a bootstrap 3.2 issue, use this jQuery snippet to address the issue:

( function($) {
  $(document).ready(function() {
    $('.navbar-collapse ul li a:not(.dropdown-toggle)').bind('click touchstart', function () {
      $('.navbar-collapse').removeClass('in');
    });
  });
})( jQuery );

I wrapped it in the proper Drupal JS stuffs.  You can just create a js file in your subtheme and add it into the .info file like this:

scripts[] = js/filename.js

**Comment by mrausch** [comment]
Thank you for this information. Unfortunately the proposed fix does not work for me. I included it in my theme and now the dropdown menu disappears after clicking on a menu link, but it does not disappear when I click on the collapse button to just close the menu. Instead the menu seems to close for a moment, then it just reopens again.

**Comment by labboy0276** [comment]
If your site is on Pantheon or somewhere I can see, please send the link and I can see whats up.

There is some funk in Bootstrap 3.2

**Comment by maxplus** [comment]
Hi,
setting jquery version to 1.10 solved the issue for me

**Comment by pirog** [comment]
1.10 works but also breaks a bunch of panels stuff like the IPE :(

On Monday, October 20, 2014, maxplus notifications@github.com wrote:

> Hi,
> setting jquery version to 1.10 solved the issue for me
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/140#issuecomment-59744770
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by maxplus** [comment]
Hi Mike,
I know but the javascript posted by labboy0276 did not work for me.

**Comment by pirog** [comment]
:( maybe @labboy0276 can work with you to get it working

On Mon, Oct 20, 2014 at 12:40 PM, maxplus notifications@github.com wrote:

> Hi Mike,
> I know but the javascript posted by labboy0276 did not work for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/140#issuecomment-59827110
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
@maxplus Can you link me to your site?

**Comment by maxplus** [comment]
Hi John,

the site is http://www.houvanhaar.be.
Thanks for helping me out!

**Comment by labboy0276** [comment]
@maxplus The problem is your class in your nav is not changing on click

``` html
<nav class="navbar-collapse collapse in" role="navigation">
```

That is always staying the same when you click the li > a

``` html
<a href="http://www.houvanhaar.be/home#two" title="" class="leaf" role="menuitem">BOEKVOORSTELLING</a>
```

Try removing the leaf class from your links and see if this helps any

**Comment by sphism** [comment]
I'm having the same problem after just updating kalatheme and panopoly yesterday...

**Comment by thiagodemellobueno** [comment]
@robloach, I believe we have a fix to this involving jquery update, and some cleverness?

**Comment by soniktrooth** [comment]
Much more modern versions of jquery are usable now due to updates to jquery_update and panopoly. I'm going to assume this one is fixed.
