### ISSUE TITLE
Looking for a kalatheme guru to help me build a theme

### ISSUE THREAD

**Issue by shawnholt** [drupalprojects/kalatheme#141]
I'm a system builder - have solid understanding of bootstrap, panels, kalatheme, etc. concepts but writing code is not my thing.  Looking for a few hours consulting to help me with styling and general support.  may hand-off some parts, or work collaboratively.  This is not a big project, but hitting crunch time.  Please let me know if anyone with kalatheme/panopoly experience has a few hours availability in the near term.  Thanks, S.

**Comment by reynoldsalec** [comment]
@shawnholt I'm closing this out since it's been a couple months, but feel free to re-open if you still want the calling card out!
