### ISSUE TITLE
Kalatheme css overiding styles in the Panels IPE settings pages

### ISSUE THREAD

**Issue by tolusonaike** [drupalprojects/kalatheme#142]
While trying out panopoly with kalatheme, i noticed the settings pages for the in-place-editor are using kalatheme styles. Not sure this is expected behavior.

**Comment by andrewmallis** [comment]
@tolusonaike – are the overrides causing any problems?

**Comment by soniktrooth** [comment]
@tolusonaike This is expected behaviour from our end. Please reopen if there's something particular that is causing an issue and we can investigate
