### ISSUE TITLE
adding navbar-fixed-top doesn't work

### ISSUE THREAD

**Issue by parijke** [drupalprojects/kalatheme#143]
I am using a (latest) dev version of Kalatheme-7.x.4.x-dev

When I add the class navbar-fixed-top to the navbar it does not work like I expected.

I cannot figure out why it isn't working so any suggestions are welcome

**Comment by parijke** [comment]
It is because this is in kalatheme.min.css

.navbar-fixed-top {
   position: static;
}

why?

**Comment by mrausch** [comment]
I simply override this in my main.css file for my custom theme. 

.navbar-fixed-top {
    position: fixed;
}

then it works again. It would be interesting to know though why kalatheme makes it static in the first place.

**Comment by pirog** [comment]
not positive but i think this was done because of the navbar module.

On Mon, Sep 29, 2014 at 5:34 AM, Michael Rausch notifications@github.com
wrote:

> I simply override this in my main.css file for my custom theme.
> 
> .navbar-fixed-top {
> position: fixed;
> }
> 
> then it works again. It would be interesting to know though why kalatheme
> makes it static in the first place.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/143#issuecomment-57153758
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by maxplus** [comment]
I did the same as mrausch and that works for me

**Comment by parijke** [comment]
Yes, I also overrode this. That is not the issue. I was wondering why this differs from standard bootstrap and do I have to prepare for more deviations from the standard bootstrap css. Now I had to find out debugging, whichs s quite ineffective.

Forgive me my English, not my native lang

**Comment by pirog** [comment]
Again, I believe this is due to collisions with the navbar module

On Tuesday, October 21, 2014, Paul Rijke notifications@github.com wrote:

> Yes, off course I also overrode this. That is not the issue. I was
> wondering why this differs from standard bootstrap and do I have to prepare
> for more deviations from the standard bootstrap css. Now I had to find out
> debugging, whichs s quite ineffective.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/143#issuecomment-59903252
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by andrewmallis** [comment]
closing in favor of #136
