### ISSUE TITLE
Main menu item not active when viewing a child page with level +2

### ISSUE THREAD

**Issue by dariogcode** [drupalprojects/kalatheme#144]
This happen when you have a tree menu of more than 2 level deepth. 
- Home
- Services
  - Services 1
    - Sub Service 1
  - Service 2
    - Sub Service 2
- Products

If you enter in Sub Service 1 the main menu item Services loss the active class.

I found this happen because we're using 2 level depth in

```
$main_menu_tree = array();
$main_menu_tree = menu_tree_all_data('main-menu', NULL, 2);
```

Then the tree doesn't have the info of the current active trail. I replaced this in my template with the following code, I know this isn't efficient but is all what I can do now:

```
  // Get the entire main menu tree.
  $main_menu_tree = array();
  $main_menu_tree = menu_tree_all_data('main-menu', NULL);

  // Only keep 2 level
  foreach ($main_menu_tree as &$menu_item) {
    if (isset($menu_item['below']) && is_array($menu_item['below'])) {
        foreach($menu_item['below'] as &$menu_item_bellow) {
            if (isset($menu_item_bellow['below'])) {
                $menu_item_bellow['below'] = array();
            }
        }
    }
  }

  $variables['main_menu_expanded'] = menu_tree_output($main_menu_tree); 
```

And finally in the implementation of theme_links__system_main_menu I added the following code inside the $links loop to check if the current link have the "in_active_trail" flag

```
 if (isset($link['#original_link']['in_active_trail']) && $link['#original_link']['in_active_trail'] && !in_array('active', $class)) {
        $class[] = 'active';
      }
```

I hope someone can reproduce this and make a correct implementation of the code I posted. 

Thanks for the awesome work!

**Comment by npoku** [comment]
Thanks for this. But just so you know there is a typo on your line:

if (isset($menu_item_bellow['below']))

Below is spelt wrong (you have 2 Ls) or is it intentional?

Thanks.

**Comment by dariogcode** [comment]
@npoku, sorry I don't understand what you mean. What is the typo error?

**Comment by soniktrooth** [comment]
We are leaving the menu depth at 2 but I have added a page that describes how to extend this from a sub theme.
