### ISSUE TITLE
Drush command error: Could not download custom library when using simplex

### ISSUE THREAD

**Issue by carsonblack** [drupalprojects/kalatheme#15]
I got the following error message when I tried to create a new subtheme based on the Bootswatch simplex theme using "drush kalatheme "Camps" --fonts --custom=simplex":
Could not download custom library.

**Comment by labboy0276** [comment]
This has been fixed with all the bootswatch based themes

**Comment by bassettsj** [comment]
@carsonblack try out 7.x-4.x and see if your issue has been resolved. I am going to close this for now though :+1:

**Comment by carsonblack** [comment]
Will do after I'm done eatin my sammich. ;-)

**Comment by bassettsj** [comment]
:+1;—

**Comment by pirog** [comment]
Seems to work for me!
