### ISSUE TITLE
Media queries breakpoints in bootstrap not working properly

### ISSUE THREAD

**Issue by schasoli** [drupalprojects/kalatheme#151]
Hello,
somehow I do not get the css breakpoints working properly with a default custom bootstrap 3.2.0 css
@screen-xs  is  set to 480px but col-xs- is used until 920px
@screen-sm is  set to 768px  but col-sm- is used until 1190px with container 750px
@screen-md  is set to 992px  but col-md is used until 1440px with container 970px
@screen-lg    is set to 1200px
So I end up with a 750px container on a 1024px screen using sm colums.
I checked if the right css is used (yes) and have no clue whats going wrong here.
any hints?

**Comment by pirog** [comment]
Is this not how bootstrap is supposed to work?

On Sunday, October 12, 2014, schasoli notifications@github.com wrote:

> Hello,
> somehow I do not get the css breakpoints working properly with a default
> custom bootstrap 3.2.0 css
> @screen-xs is set to 480px but col-xs- is used until 920px
> @screen-sm is set to 768px but col-sm- is used until 1190px with container
> 750px
> @screen-md is set to 992px but col-md is used until 1440px with container
> 970px
> @screen-lg is set to 1200px
> So I end up with a 750px container on a 1024px screen using sm colums.
> I checked if the right css is used (yes) and have no clue whats going
> wrong here.
> any hints?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/151.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by schasoli** [comment]
hm, 
on 800px I would expect screen-sm but get screen-xs
on 1024px I would expect screen-md but get screen-sm
on 1400px I would expect screen-lg but get screen-md

well, I play a bit with the breakpoints now

**Comment by schasoli** [comment]
strange enough. I ended up with https://github.com/Teachnova/bootstrap and now the breakpoints are working as expected.
adding this after `.make-grid(xs);` in grid.less gives a new grid system for large phones (or small horizontal ones)

> // hs grid
> // Columns, offsets, pushes, and pulls for the small device range
> // from screen-hs-min until screen-sd-min:
> @media (min-width: @screen-hs-min) {
> .make-grid(hs);
> }

I love this

**Comment by pirog** [comment]
Oh very cool! I'll have to check that out

On Tuesday, October 14, 2014, schasoli notifications@github.com wrote:

> strange enough. I ended up with https://github.com/Teachnova/bootstrap
> and now the breakpoints are working as expected.
> adding this after .make-grid(xs); in grid.less gives a new grid system
> for large phones (or small horizontal ones)
> 
> // hs grid
> // Columns, offsets, pushes, and pulls for the small device range
> // from screen-hs-min until screen-sd-min:
> @media https://github.com/media (min-width: @screen-hs-min) {
> .make-grid(hs);
> }
> I love this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/151#issuecomment-59005280
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
