### ISSUE TITLE
sub-theme bootstrap issue

### ISSUE THREAD

**Issue by heatherfarrier** [drupalprojects/kalatheme#159]
Is there an issue when generating more than one subtheme through the admin panel? I have three subthemes that I generated from the admin panel. One of my subthemes is not inheriting bootstrap from Kalatheme nor will it recognize the the custom bootstrap library that I added to /sites/all/libraries/subtheme_bootstrap/. If I manually include a link to the bootstrap CDN, the subtheme works great. Otherwise, the theme breaks.

I suspect something went wrong during the sub-theme generation. The .info file specs kalatheme as the base theme. Any ideas or advice on how to resolve this?

**Comment by labboy0276** [comment]
Most likely has to do with issue #119

**Comment by soniktrooth** [comment]
Closing as a duplicate of #119
