### ISSUE TITLE
Kalacustomize styles don't work

### ISSUE THREAD

**Issue by pirog** [drupalprojects/kalatheme#16]
this is reported by @wardshark

These don't work any more:
Float Left, Float Right, Clearfix, Jumbotron, Well

**Comment by boTux** [comment]
The class added in the theme settings doesn't works either.
On version : Kalatheme 7.x-3.0-rc3+74-dev

**Comment by pirog** [comment]
let's make sure this gets rolled into 3.x as well!

**Comment by bassettsj** [comment]
Should I open a pull request there?

**Comment by pirog** [comment]
That works... also fine with you just cherry picking 2dc79ec from master is that is easier.

**Comment by bassettsj** [comment]
Sweet, will do that.
