### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'kalatheme_run_install' not found or invalid function name in authorize_run_operation() 

### ISSUE THREAD

**Issue by tomosaigon** [drupalprojects/kalatheme#163]
Trying out 7.x-4.x-dev today, when trying to "Build and enable a custom subtheme" I get this:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'kalatheme_run_install' not found or invalid function name in authorize_run_operation() 

And the subtheme isn't created.

**Comment by drewhendricks** [comment]
We are getting this same error.  Did you ever find a solution?

**Comment by Iceabenezer** [comment]
Same issue here. Can't do this manually or through the UI

**Comment by RobLoach** [comment]
@tomosaigon @Iceabenezer Are you still running into this issue? Is it persistent on the 3.x branch?

We are considering deprecating 4.x and bringing any of the highlighted changes back.

**Comment by Iceabenezer** [comment]
@tomosaigon Yep! Just tried this again on a new install and it still happened. I will try the 3.x branch

**Comment by Iceabenezer** [comment]
Never mind. I was using the 3.1 release

**Comment by stadulis66** [comment]
I have tried all dev and current versions and none of them work.  Is it possible to make a subtheme manually? This is really slowing me down. Thanks!

**Comment by soniktrooth** [comment]
@stadulis66 Can you tell me exactly what version(s) you're trying and what the errors are?

**Comment by stadulis66** [comment]
Hi Josh - Yes.  The error I get is Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'kalatheme_run_install' not found or invalid function name in authorize_run_operation() (line 304 of /var/www/stg.oceansbeyondpiracy.org/htdocs/includes/authorize.inc).

Drupal:  7.43
Kalatheme 7.x-3.1 (default theme) - but have tried bunch of other versions

Thanks for your help with this.  On a side note, this can be done with Drush?  If so, what are the drush commands?  Thanks,  Michael

**Comment by stadulis66** [comment]
I was able to get it built with drush command no problem.
