### ISSUE TITLE
Custom bootstrap library not compatible with xautoload

### ISSUE THREAD

**Issue by gease** [drupalprojects/kalatheme#164]
Xautoload uses hook_custom_theme to load libraries defined in themes. This is definitely not what kalatheme expects - at this stage $theme_key is not yet defined - so kalatheme fails to understand that custom library should be used. And this cannot be fixed without major revisiting of kalatheme bootstrap process (how it loads its .inc files and how custom theme is checked there).

**Comment by pirog** [comment]
does this spit out an error or other relevant message that could be helpful?

**Comment by gease** [comment]
No error, I think I described above the source of problem (which I discovered with ddebug_backtrace). If you'd like, I can describe what I've found in personal communication.

**Comment by soniktrooth** [comment]
@gease This isn't really on our radar at the moment but we would definitely check out  patches if you have the time for that. If you are going to do that can you comment to let us know what version of KT you would be working on.

**Comment by andrewmallis** [comment]
https://www.drupal.org/project/xautoload is not on our radar
