### ISSUE TITLE
Overriding kt-navbar.tpl.php

### ISSUE THREAD

**Issue by UTANdev** [drupalprojects/kalatheme#166]
I don't like the way Kalatheme slaps a Home link with the site name at the beginning of the main navigation. I placed a modified copy of kt-navbar.tpl.php in my subtheme's root and cleared cache, but there's no effect. What am I missing?

**Comment by npoku** [comment]
It worked for me. How did you flush out your cache? And what I did was I kept the same file structure as Kalatheme had it. So I placed my file in Subtheme > templates > bootstrap > kt-navbar.php.

You might have to create some of the folders in the suggested path above.

**Comment by UTANdev** [comment]
I tried your suggestion and it works, but then moved my template back to its original location (subtheme root), cleared caches, and my template also gets picked up at that location. So I don't know what happened between 22 days ago and now, but the issue is closed.
