### ISSUE TITLE
UI subtheme generation ends with error

### ISSUE THREAD

**Issue by aDarkling** [drupalprojects/kalatheme#167]
Installed Kalatheme 4.alpha on a new plain Drupal Installation with panapoly_theme, jquery_update, and views installed.

Tried to create a subtheme.  It took me to a page requesting ftp information.  After I supplied it, it went back to admin/appearance & gave this error:

Error message Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'kalatheme_run_install' not found or invalid function name in authorize_run_operation() (line 304 of /var/aegir/platforms/drupal-7/includes/authorize.inc).

**Comment by korzh-nick** [comment]
If you select the Bootstrap library. as the default, then the problem can be avoided

**Comment by andrewmallis** [comment]
Our alpha is still in flux and a bit of an experiment, sorry for the rough patch. We'll be looping back around to 4.x soon.
