### ISSUE TITLE
Clean install with kalatheme throws Fatal error: Class 'views_plugin_style' not found

### ISSUE THREAD

**Issue by parijke** [drupalprojects/kalatheme#17]
Clean install

Then 
drush dl kalatheme
drush kalatheme "mytheme" fails with this error

**Comment by parijke** [comment]
Manual installed the mentioned requirements, but it still says Fatal error: Class 'views_plugin_style' not found

**Comment by pirog** [comment]
@parijke does this happen on latest 3.x dev?

**Comment by pirog** [comment]
@katypool can you work with @parijke to provide steps on how to replicate this error on the 3.x branch? If the error exists on 3.x as well open up a new ticket for this issue for 3.x and set the milestone for 7.x-3.0 release.

**Comment by pirog** [comment]
@parijke @katypool this seems to not happen to me using views 3.8

**Comment by parijke** [comment]
Reproduced my own steps with latest dev. It does not happen anymore.
Steps I did:
clean drupal 7.28
drush dl libraries-7,x-2.1 panels views ctools jquery_update panopoly_theme
drush en panels views libraries jquery_update
in admin interface set jquery on 1.7
enabled kalatheme and set to default 

drush kalatheme "My Awesome Theme" --fonts

Command kalatheme needs the following module(s) enabled to run:      [error]
kalatheme.
The drush command 'kalatheme My Awesome Theme' could not be executed.[error]

Then I created manually the sites/all/libraries directory
drush cc all

drush kalatheme "My Awesome Theme" --fonts

kalatheme subtheme "My Awesome Theme" created in: /home/mkbeyond/public_html/kalatheme.dev/sites/all/themes/my_awesome_theme.

So, I can't seem to reproduce the error again with the latest dev AND the newer version of views. Now I am back in th saddle with kalatheme as I had to skip it for my last project.

**Comment by pirog** [comment]
Awesome! I think the libraries issues is resolved in the latest dev now as well.

**Comment by ForestMars** [comment]
What was the solve for this issue? I just tried on 3 different installations, including an install of 7.38 with nothing except panels, views, libraries, etc, and Kalatheme was throwing this fatal error as soon as it was enabled.

**Comment by andrewmallis** [comment]
@ForestMars are you getting

`Fatal error: Class 'views_plugin_style' not found`

please confirm Kalatheme version
