### ISSUE TITLE
Theme-Search

### ISSUE THREAD

**Issue by jannickfahlbusch** [drupalprojects/kalatheme#175]
Hey,

i know, this ticket may sound a little bit strange. 

I'm searching a theme from Kalatheme, wich i used before my website went down. Sadly i don't remember the settings i did in Kalatheme... 
I'm googled a while but there seems no way to find it.

I'm asking for your help, to identify it.

I don't have more screenshots of it, but i hope, some of you can still identify the Bootstrap-Theme i used.

I know, that this theme had Font-Awesome included. Also it was pretty colored (mostly red, orange, and turquoise as background), the headers were colored in yellow. 

As you can see in the pictures, the headers also had some ornaments, wich made them look so good.

So i hope you can help me, to find this theme.

Thanks in advance, 
Jannick

**Comment by reynoldsalec** [comment]
Hey @jannickfahlbusch, that looks like the [Amelia theme](http://bootswatch.com/2/amelia/) from Bootswatch. Hope that helps!

**Comment by jannickfahlbusch** [comment]
Thank you! That is exactly what i searched :+1:
