### ISSUE TITLE
Malformed URL getting library

### ISSUE THREAD

**Issue by aangelinsf** [drupalprojects/kalatheme#176]
Sometime over the weekend Bootswatch API starting returning https: for its urls. In template.php, that breaks the following:
        drupal_add_css($base['scheme'] . ":" . $css, 'external');

A workaround for me is:
      if (strpos($css, 'http') <> 0) {
        drupal_add_css($base['scheme'] . ":" . $css, 'external');
      }
      else {
        drupal_add_css($css, 'external');
      }

**Comment by pirog** [comment]
Nice! great to know.

@labboy0276 @soniktrooth maybe one of you guys can hit up a quick PR for this?

**Comment by reynoldsalec** [comment]
Just confirming that other folks have had this issue and that a quick fix would be nice to allay the pain.

**Comment by soniktrooth** [comment]
@reynoldsalec @pirog I will look into it this afternoon.

**Comment by pirog** [comment]
I think @soniktrooth has dealt his judgement unto this issue and its fixed in dev now.

**Comment by GuiguiSurLinux** [comment]
I think this stll needs to be fixed in 4.x

**Comment by pirog** [comment]
@soniktrooth? i thought you merged this into 4.x as well? maybe im thinking of something else such as how awesome taylor swift is?

**Comment by soniktrooth** [comment]
I thought it was as well. You keep thinking about TS and I'll track down what happened.

**Comment by soniktrooth** [comment]
Sorry @gboudrias it looks like there's something up with hubdrop so this never got pushed to drupal.org. This commit (https://github.com/drupalprojects/kalatheme/commit/62fa410d0804b056b80858bb7bb3c177787b606f) was merged here already but needed a little extra help to make it onto d.o. It should be up there now.

**Comment by GuiguiSurLinux** [comment]
Awesome, keep up the great work guys!
