### ISSUE TITLE
Add sass implementation of 3.x or 4.x

### ISSUE THREAD

**Issue by dariogcode** [drupalprojects/kalatheme#18]
I'm trying to implement the sass_kaltheme version (https://github.com/kalamuna/sass_kalatheme), however I just noticed this is in version 1.x 

Is there possible to support SASS/Compass for 3.x or 4.x version?

Thanks for the good work you're doing.

**Comment by bassettsj** [comment]
Hey the 4.x has SASS included with build tools. More information to come soon. Stick tight my friend!

**Comment by dariogcode** [comment]
Oh, that was fast. Thanks!. I didn't know this feature for 4.x. Is this version stable, something we can start using in our next projects?

**Comment by bassettsj** [comment]
Not quite yet, but you could help check it if you want. It is here under 7.x-4.x branch.
