### ISSUE TITLE
subtheme_bootstrap library does not load

### ISSUE THREAD

**Issue by tchopshop** [drupalprojects/kalatheme#188]
I want to manually load my bootstrap library and it's not working. I have checked all the paths and directories and the version of bootstrap. Nothing works.

**Comment by andrewmallis** [comment]
Please describe what you have tried, confirm your paths, and your methods for including bootstrap. Please also specify the versions of Kalatheme, Boostrap, and jquery_update you are running.

**Comment by tchopshop** [comment]
Below are screenshots of directory for bootstrap library and of theme settings for my sub theme, which shows jquery version. Bootstrap v3.3.4. Kalatheme 3.1

![screenshot_65](https://cloud.githubusercontent.com/assets/1149398/8992599/1715efa6-36c5-11e5-93d5-884277f43da0.png)

![screenshot_66](https://cloud.githubusercontent.com/assets/1149398/8992660/650dd2fa-36c5-11e5-88b4-f52ec2f0b2da.png)

**Comment by labboy0276** [comment]
Try switching your admin theme to seven to see if the lets you build a custom subtheme.  Also, try setting jquery version to 1.7 for the backend if that doesn't work.

**Comment by andrewmallis** [comment]
where is `baseline_boostrap` located, exactly?
have you created a subtheme of kalatheme?

**Comment by tchopshop** [comment]
I don't want to be forced to make a custom subtheme via a ui. Do I have to?
I have a theme called baseline in sites/default/themes that was using radix, I changed the parent theme to be kalatheme.

**Comment by labboy0276** [comment]
You don't have to do it, but it is fairly painless.  Also, usually you don't put any modules or themes in sites/default unless you are running a multisite.  Are you running a multisite?

Can you post your subtheme .info file here please.  Then I can probably see why it isn't working for you.  

Also where did you put the baseline_boostrap library.

**Comment by tchopshop** [comment]
I'm sorry I mis-wrote... it's in the normal place... sites/all/themes... I'd never put a theme in "default". baseline_bootstrap is in libraries at sites/all/libraries --- where else would it go?

Here's the info file. Very basic.

![screenshot_68](https://cloud.githubusercontent.com/assets/1149398/9010911/84106942-376f-11e5-89e5-9a429981aef8.png)

**Comment by labboy0276** [comment]
It wouldn't go anywhere else usually, so you win.  

This all looks ok to me.  

So this theme isn't showing up in your appearance section?  Have you tried the usual stuff: drush cc all, drush rr, etc

**Comment by tchopshop** [comment]
No, the theme is showing up fine, but it isn't loading bootstrap css or js files from the library, so it's very ugly.

I can load the files via the bootstrap library module, but was trying to do it your way.

**Comment by labboy0276** [comment]
is it just not showing the bootstrap css / js in the admin / backend or is it throughout the site?

**Comment by tchopshop** [comment]
Throughout the site. I've tried different permissions for the libraries folder too.

**Comment by labboy0276** [comment]
Is there any errors in your watchdog or console logs that are not worthy?  

Have you tried an older version of bootstrap, like 3.2?

What version of jquery update are you running?

**Comment by tchopshop** [comment]
Thank you for all your incredible responsiveness. I'm just having to move very fast on this and the problems weren't making me feel good about it. I'll probably test it again later on a pristine site, rather than one that is already mostly built. 

Even more importantly (because I could use bootstrap library module to load the bootstrap files) was that I also couldn't get menu outputted anchor links to work -- kalatheme was giving me a fatal error -- and they were working fine with the main bootstrap theme. I'm trying to build a site which will use long "parallax-type" landing pages in panels for organic group landing pages.

**Comment by labboy0276** [comment]
Can you try and use the subtheme installer to see if it just works? 

Trying to pinpoint what is wrong, it is hard when I cant see the code or logs.  What version of jquery_update are you using?

**Comment by thiagodemellobueno** [comment]
Closing due to no reply.
