### ISSUE TITLE
Kalatheme + Panopoly 1.3 or greater + Libraries 2.2 = FAIL

### ISSUE THREAD

**Issue by labboy0276** [drupalprojects/kalatheme#19]
This has been a problem since Panopoly stared tolling out new updates recently.  I know I have talked about it a few times, but here it goes again.  This happens in both Kalatheme 1.4 and 3.x as a FYI.  When upgrading to a version of Panoply greater than 1.2, the 2.2 libraries seems to throw Kalatheme off.  I have gotten a variety of erros like:

Notice: Undefined index: post-load integration files in libraries_load_files() (line 697 of /var/www/csi-america/profiles/panopoly/modules/contrib/libraries/libraries.module).
Notice: Undefined index: post-load integration files in libraries_load_files() (line 775 of /var/www/csi-america/profiles/panopoly/modules/contrib/libraries/libraries.module).
You do not have a Bootstrap library installed but that is ok! To get equipped either check out our Start Up Guide or run our Setup Wizard.

and the screenshot attached.
![panop fail](https://cloud.githubusercontent.com/assets/5560907/3105234/b6cee2ba-e670-11e3-987b-6eb64b2aab84.png)

It seems that the new libraries 2.2 does something with file perms and kalatheme can no longer read the directory.  

The work around is to just downgrade to libraries 2.1 and all is well, but something is not kosher here.

**Comment by pirog** [comment]
Submit a pull request and fix that shit!

**Comment by labboy0276** [comment]
murica

**Comment by bassettsj** [comment]
Gasp!

**Comment by bassettsj** [comment]
@pirog This one is critically important. I am not sure how to best tackle this one. Want to try powowing on this one to get 3.x & 4.x stable(r)?

**Comment by pirog** [comment]
@bassettsj agreed. let me try to plow through some stuff i have to do ASAP for Kalabox and if i have time we can give it a look see. 

If not, i wont be in tomorrow but i think @reynoldsalec or @labboy0276 can help.
