### ISSUE TITLE
Kalacustomize documentation

### ISSUE THREAD

**Issue by kenrbnsn** [drupalprojects/kalatheme#190]
I am using Kalatheme for the first time and I've been searching for documentation on how to add styles to Kalacustomize. Everything says you can easily add styles, but nowhere is there a "how to".

Thanks in advance.

**Comment by soniktrooth** [comment]
@kenrbnsn Is this what you're looking for? https://github.com/drupalprojects/kalatheme/wiki/Styles-Plugin

**Comment by kenrbnsn** [comment]
That helped. I had seen it before, but it didn't make any sense. The screen shots are too small to be seen on a laptop screen & they can't be enlarged.
