### ISSUE TITLE
Admin menu preventing left clicking with subthemes

### ISSUE THREAD

**Issue by ellastelter** [drupalprojects/kalatheme#195]
After I build a subtheme I can no longer left click on anything, and must right click, open in new window to navigate.  I can't use buttons at all.  I tried used a third party bootstrap library and then Cosmos, but I am still having the issue.  The only thing that responds is the top layer of the admin menu.  

If I am not logged in, things seem to work just fine.  

I am going to continue troubleshooting, and will update if I have any progress.

**Comment by labboy0276** [comment]
Hello again

So, this is a JQuery Issue and a Bootstrap issue.  I would try 2 things here:
1. Update Jquery Update to 3.0-alpha2.  Set the JQuery version to 1.10 and click to enable the JQuery Migrate.  If that doesn't work...
2. Try using a Bootstrap 3.2 library instead.  I can email you one if you can;t find one.

**Comment by ellastelter** [comment]
#1 worked for me.  

I have Panopoly, which warns me against manually updating module included in the distribution, but it hasn't caused me any issues so far.  

Thanks again!!

**Comment by labboy0276** [comment]
No problemo

**Comment by soniktrooth** [comment]
Sounds like everyone is happy. Closing.
