### ISSUE TITLE
Can't add custom library to existing subtheme

### ISSUE THREAD

**Issue by soniktrooth** [drupalprojects/kalatheme#203]
I tried uploading a custom bootstrap library and nothing happened.

For starters it seems to want a zipped file. Uploading anything else seems to make it crash and burn. We should adjust the help text to make this clear. 

After uploading a zip I assumed it was going to copy css out of the zip file and stick it in the theme but it seems nothing happens.

**Comment by soniktrooth** [comment]
@pirog can you confirm for me that this is the expected behaviour? Is there some sort of folder convention that needs to be followed? I noted that it says in the help text disclaimer that it doesn't work well with all libraries. I used a http://startbootstrap.com one—bad idea?

**Comment by soniktrooth** [comment]
Ok, I think I got the hang of what's going on here. It seems you have to check 'Build and enable a custom subtheme' in order for this to work. So it would seem that the real issue is that you can't add a custom library to an existing subtheme.

**Comment by andrewmallis** [comment]
https://github.com/drupalprojects/kalatheme/wiki/Using-custom-Bootstrap-Libraries

**Comment by soniktrooth** [comment]
@andrewmallis I'm not seeing anything in the docs regarding the issue. It seems to me that the the forms for adding a custom library shouldn't exist on a subtheme settings page.

**Comment by soniktrooth** [comment]
I've played with this a bit more and the UI is confusing. In order to use a custom or third party theme as listed in the drop down you have to build a custom subtheme by checking the checkbox in the other fieldset. I'm thinking this drop down should be in the fieldset below and only show when the 'build and enable custom subtheme' checkbox is checked—along with the others. We probably still need a drop down here though to allow for a user to choose between vanilla boostrap, the library they chose when building the subtheme, or no Bootstrap at all.

**Comment by soniktrooth** [comment]
I've been toying with this a little and I feel like this is going to be a lot of work (read testing) to move the drop down. I think a temporary fix for this would be adding something to the description under the dropdown. Putting together a PR with this approach so that this issue can be satisfied.

**Comment by andrewmallis** [comment]
I don't think we want to support this feature.
The UX improvements you propose @soniktrooth seem more appropriate to me, and should be the subject of a new and more focused issue. Once that issue exists, we can resolve this one.

**Comment by soniktrooth** [comment]
#223 Addresses the UX improvements
