### ISSUE TITLE
Views row class

### ISSUE THREAD

**Issue by soniktrooth** [drupalprojects/kalatheme#208]
Seriously, why does this code exist? I've had to remove it or override it from every Kalatheme site I've worked on.  

```
function kalatheme_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  // Add a .row class to wrap .views-row.
  $variables['view_content_class'] = 'view-content';
  if ($view->style_plugin->plugin_name != 'list') {
    $variables['view_content_class'] .= ' row';
  }
}
```

This is adding a `row` class to every View that is using the list display, however in every case I've come across there is already a `row` wrapping the view and it makes things hang out in the margins. 

I can see it being useful in some very specific use cases but it seems an odd thing to be included in Kalatheme. 

@pirog do you have any context on this? If not I'm going to nuke it.

**Comment by pirog** [comment]
@soniktrooth NFI.

PURGE!

**Comment by soniktrooth** [comment]
I will burn it with fire.

**Comment by labboy0276** [comment]
thank goodness

**Comment by pirog** [comment]
the purest death is one by fire

**Comment by andrewmallis** [comment]
pull request @soniktrooth ?

**Comment by soniktrooth** [comment]
@andrewmallis ^^

**Comment by andrewmallis** [comment]
:+1:

**Comment by soniktrooth** [comment]
#212 wasn't enough—we need to remove the views-view.tpl as well

**Comment by andrewmallis** [comment]
Well, what are you waiting for @soniktrooth an invitation?
Seriously, though, good eye.

**Comment by soniktrooth** [comment]
Just an opportunity—I found this in the middle of something else so I was just commenting so I wouldn’t forget.

**Comment by amp9020** [comment]
Hi, @soniktrooth , I'm receiving "Notice: Undefined variable: view_content_class in include() (line 55 of /sites/all/themes/kalatheme/templates/views/views-view.tpl.php) .  Is this related to this post? (I saw your comment on Oct 16).   For now can I remove line 55 manually or define a blank variable?

Thanks,

**Comment by soniktrooth** [comment]
@amp9020 Sorry about this one—I haven't had a chance to get back to this. You can, in fact, remove the views-view.tpl.php entirely because the only customization that Kalatheme makes is the adding of that variable, which is now, of course, undefined.

**Comment by amp9020** [comment]
@soniktrooth Even better to remove the file.  That worked.  Cheers!  Thanks, no more messages about that in watchdog ^_^
