### ISSUE TITLE
Views content pane display does not grid properly

### ISSUE THREAD

**Issue by katypool-zz** [drupalprojects/kalatheme#21]
The content pane display does not display the grid format. Instead it shows the content all in one column like an unformatted list. http://dev-citc.at.kalamuna.com/staff

**Comment by pirog** [comment]
Thanks for finding this! 

What version? Can you maybe post some screenshots of your views config and the resulting page?

**Comment by katypool-zz** [comment]
![image](https://cloud.githubusercontent.com/assets/7318014/3273647/a1d3112a-f326-11e3-910d-62f38f1c8ddf.png)

![image](https://cloud.githubusercontent.com/assets/7318014/3273690/f1b3be92-f326-11e3-9ce6-54c5a157608f.png)

![image](https://cloud.githubusercontent.com/assets/7318014/3273656/cb969608-f326-11e3-87e5-b214fdcc58f3.png)

Hope that is helpful!

**Comment by pirog** [comment]
Yes! Definitely helpful! 

Maybe we can look at this 2getha next time you are at KALAMUNA HQ.

and yes i just used 2getha.

**Comment by bassettsj** [comment]
Seems like it is an issue with views 3.7, updated the module and resolved the issue.

**Comment by katypool-zz** [comment]
think I figured it out
CSS says div class="gridcol gridborder col-1 col-item-4 col-xs-12 col-sm-12 col-md-4 col-lg-12 "
shd be div class="gridcol gridborder col-1 col-item-4 col-xs-12 col-sm-12 col-md-4 col-lg-4 "
each item is taking up all 12 grid columns on large devices. It works when I make the window "medium" sized!

**Comment by bassettsj** [comment]
@katypool,

install this module in the meantime: [views_bootstrap](https://drupal.org/project/views_bootstrap)

**Comment by pirog** [comment]
@katypool can you try this out on the latest dev version of 3.x and see if it resolves your issue? If not please reopen!

**Comment by pirog** [comment]
@bassettsj is this issue supposed to be for 4.x or 3.x? I am going to say it is 3.x since we are getting rid of this in 4.x? 

Going to make the switch but please revert or open new issue if this is not accurate.

**Comment by katypool-zz** [comment]
With views_boostrap installed, the Boostrap Grid format works great!
