### ISSUE TITLE
Thoughts on where to go

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#22]
Greetings, @carsonblack heard you have a lot thoughts on what could be improved with kalatheme, so I thought I would start an issue about it to get a conversation going.

**Comment by pirog** [comment]
RANDOM THOUGHT:
With me focusing on Kalabox i feel there are a lot of unresolved issues in the 3.x branch. It would be great to find someone to help resolve this issues so @bassettsj can focus full throttle on the 4.x sauce.
