### ISSUE TITLE
Host project and documentation on drupal.org

### ISSUE THREAD

**Issue by Francewhoa** [drupalprojects/kalatheme#230]
Hi there project maintainer(s) :)

Our team is currently evaluating the possibility of making a large investment in time and energy into Kalatheme. Mostly in form of free contributions, such as suggested patches, and documentation.

But the main blocker we're facing is that Kalatheme project, documentation, and issues/tickets are currently hosted on Github :(

Github is owned by a Corporation. Compare to Drupal.org which is owned by you the community users and the not-for-profit Drupal Association (DA). The DA first priority is to serve you the users. Drupal.org is not owned by a Corporation. So no interference from Corporations. Corporations are really welcome but as contributors. Not owner.

More benefits of hosting your project on drupal.org at https://www.drupal.org/node/648898

Have you considered hosting your project on drupal.org?

Cheers,

Francewhoa

**Comment by Francewhoa** [comment]
![community_owned-corporation_owned-comparison-v02](https://cloud.githubusercontent.com/assets/119942/11225504/56d9513a-8d2f-11e5-8ac8-1837e5ff6781.png)

**Comment by pirog** [comment]
1. Get better collab tools on drupal.org and sure
2. I think your analogy of the DA as the green fishes is fairly optimistic.

**Comment by Francewhoa** [comment]
Hi all :) Here is the details version of what I mean by "community owned" versus "corporation owned" tools

Drupal.org forums first priority is to **serve you the users**. Github first priority is to **serve their shareholders by hoarding money for them**.

I suggest to Drupal users to consider using community **owned** tools instead of corporate **owned** tools. Because the first priority of community **owned** tools is to serve you the users ;)

---

Here are some benefits of community **owned** versus corporation **owned**

An increasing number of people realized that the Drupal community first priority is to serve you and all its users. Compare to Corporations, where their first priority is to serve their stakeholders. Corporations do so by hoarding money for their stakeholders. Yes serving the Community is often on a Corporation list of priorities but it's a much lower priority ;)

For example, when a Corporation is facing a challenging decision and have to choose an higher priority between:

• Option 1: Increase their profit/Hoard more money; 
• Option 2: Serve the interest of the Community. 

Then most Corporations will not hesitate to go with option 1. Hoarding money. One real practical example is tomorrow morning you could receive an announcement from Github saying that for now on you have to pay them money to access part of their services. Or announcing that they will provide part of your private information to third parties to increase their money hoarding. Or announcing that they will close their website because their stakeholders are unhappy with the amount of money hoarding. With a Community **owned** project you're protected against such behaviors.

As you know Corporations are really welcome in the Drupal community but as contributors. Not **owner**. 

Corporations are not able to compete with the value of Community **owned** projects. Instead, they get value by both contributing to the Community **owned** project, and hoarding money via other channels. Conditional to not interfere with the Community decision making.

One clever action early taken by Dries, the founder of Drupal, was as early as 2001, to make the Drupal project Community **owned**. While at the same time welcoming contributions from anyone, including Corporations.

Sometime a website seem to be community **owned** because it uses wording such as "Creative Commons Attribution-ShareAlike (CC BY-SA)" or "Open Source". But if you search who owns that website you will find that it is **owned** by a corporation. Not **owned** by a community. 

Here is the source that demonstrate that Github is **owned** by the corporation "GitHub, Inc." at https://en.wikipedia.org/wiki/GitHub

Source about DA being owned by a not-for-profit organization at https://assoc.drupal.org/about

**Comment by soniktrooth** [comment]
@Francewhoa Everyone here at Kalamuna is very aware of the differences between 'community owned' and 'corporation owned' and we are all big advocates of open source and the Drupal community. That being said—our choice to use Github is purely a pragmatic one. We chose to use Github so that we are able to collaborate more effectively, get more done and ultimately benefit the community to a greater degree than we could by using drupal.org.

If Github were to engage in any of the hypothetical practices that you outlined we wouldn't hesitate to make changes to our dev practices to ensure that people's information was kept private and that open nature of Kalatheme remains uncompromised.

Whilst we freely encourage any contributions you and your team can make to this open source project, unfortunately we're not able to change our current development practices in order suit your requirements.

**Comment by Francewhoa** [comment]
Thanks for your reply Josh :) We understand that Kalamuna is not interested in hosting its project on the community owned drupal.org

Github is not a viable option for our contributions though. So for the benefit of all Drupal community users we will focus our time and energy on another project hosted on Drupal.org.

As you know that was just a suggestion for Kalamuna consideration and decision. Not a request ;) Feel really free to use any tools that works best for you guys. Enjoy the corporate owned Github then :)

**Comment by soniktrooth** [comment]
We will, thanks @Francewhoa.
