### ISSUE TITLE
As of Drupal 7.50 don't drupal_get_path of a non-existing module

### ISSUE THREAD

**Issue by scottrigby** [drupalprojects/kalatheme#288]
In `kalatheme_css_alter()` there are several calls to `drupal_get_path()` for modules that may not exist on the user's system. If not, as of Drupal 7.50 a warning will be issued "The following module is missing from the file system" (see https://www.drupal.org/node/2487215 and the [change record](https://www.drupal.org/node/2581445)). I'll make a patch wrapping those in `module_exists()`, which clears up the problem.

**Comment by RobLoach** [comment]
Beat me to it! If you submit that PR, I'll merge.
