### ISSUE TITLE
Doesn't load bootstrap css in media-browser modal

### ISSUE THREAD

**Issue by miromarchi** [drupalprojects/kalatheme#296]
Hi, I am trying to use the media-browser widget for image fields with my panopoly based website.
If I chose my kalatheme subtheme as media-browser modal theme in /admin/config/media/browser, the theme seems not to load the proper twitter bootstrap css files, so classes present (e.g. btn btn-default) do not alter the elements.
My main.css file is correctly loaded, so I can reproduce the twitter bootstrap effects by copying the btn btn-default classes in my main.css file.
Do you have problems theming the media-browser? Any suggestions on how to theme it?
Thank you!

![drupal-kalatheme-theming-media-browser](https://cloud.githubusercontent.com/assets/5427145/20259865/74308906-aa57-11e6-97b5-55e00e4c0595.png)

**Comment by RobLoach** [comment]
@miromarchi A work-around may be to use the Seven theme as the administration theme. Media Browser has been known to cause issues across different jQuery and Bootstrap versions.

**Comment by andrewmallis** [comment]
second @RobLoach's recommendation to use seven for the media browser.

**Comment by miromarchi** [comment]
@RobLoach thanks, I did prefer to add some specific css in my kalatheme subtheme main.css file, copying something from twitter bootstrap css files. But seven was warking correctly.
