### ISSUE TITLE
Make sure d.o project's git repo is up to date

### ISSUE THREAD

**Issue by pirog** [drupalprojects/kalatheme#54]
Experiencing some issues with hubdrop so until these are sorted out please make sure you are also pushing your new commits over to the d.o repo as well. 

@jonpugh, any issues you know of on your end? 

@reynoldsalec, you might want to check to see if this is happening on hotsauce as well?

**Comment by reynoldsalec** [comment]
@pirog looks like the same issue on hotsauce; last commit to the d.o repo is from May.

**Comment by pirog** [comment]
Maybe @jonpugh can help with these deeper mysteries of the universe.

@reynoldsalec in the meantime it might be nice to put together a list of issues the completion of which will produce a 3.x release.... possibly even a stable 1.0.

**Comment by bassettsj** [comment]
@pirog Are we really loosing commits here?

**Comment by pirog** [comment]
@bassettsj i dont know what you mean by losing but it appears hubdrop hasnt sent anything to d.o in awhile. Just setting a new remote for d.o and pushing code manually should get us back N*SYNC until @jonpugh can figure things out.

**Comment by bassettsj** [comment]
Why don't we have it as part of the build control step for now? That would be easy.

**Comment by bassettsj** [comment]
``` coffeescript
module.exports =
  options:
    dir: 'build'
    commit: true
    push: true
    remote: 'git@github.com:drupalprojects/kalatheme.git'
    build:
      'Built %sourceName% from commit %sourceCommit% on branch %sourceBranch%'
  dev:
    options:
      branch: '7.x-4.x'
  release:
    options:
      branch: '<%= package.drupalversion =>'
      tag: '<%= package.drupalversion +"-"+ package.version =>'
```

**Comment by bassettsj** [comment]
It would be easy to add a couple more targets for d.o so we can push up the builds easily.

**Comment by hubdrop-user** [comment]
Jenkins restarted, folks. I'm sorry about the downtime.  Please either
reopen this issue and assign to be or yell at me through any other channels
and I will restart :)

Someday I will add supervisor to make sure Jenkins never stops running!

**Comment by bassettsj** [comment]
@hubdrop-user Thanks for the message. Will close this issue then :+1:

**Comment by pirog** [comment]
thanks @hubdrop-user 

@bassettsj until Jenkins never stops running maybe we should consider this as part of the build option if the webhook fails?

your call.

**Comment by bassettsj** [comment]
It is an easy change if needed in the future, not worried about it. We should also have a few forks out there anyways. I am going to try to encourage all development be done through a pull-request workflow so each contributor should have a fork on their profile and submit features/fixes with a pull request with travis magic going on hopefully :)

**Comment by pirog** [comment]
If you can get that happening it would be a great model/template for the rest of our dev workflows.

+1,000,000

**Comment by bassettsj** [comment]
@hubdrop-user a minor issue, but still matters, github keeps setting the "default branch" head from master to 7.x-3.x after I set it back, it only matters because I am adding public documentation to the master branch and the github repo is supposed to the development center so having the source in master be up front and center is important, do you think there is a way to keep github on master?
