### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by swiders2** [drupalprojects/kalatheme#58]
Brand new to Kalatheme, and after creating a subtheme via the admin panel tool tips aren't working.  Anybody help a brother out?

**Comment by bassettsj** [comment]
Sure @swiders2, but this is more of a bootstrap support request than a kalatheme issue, you need to "opt in" to the tooltip and popover data-api to get them going. It is easy to do. Add this to your subtheme's JS and it should init tooltips.

``` js
(function($){
  // Shorthand for $( document ).ready()
  $(function() {
    // this will activate on the targets
    $('*[data-toggle="tooltip"]').tooltip();
    $('*[data-toggle="popover"]').popover();
  });
})(jQuery)
```

**Comment by swiders2** [comment]
thanks!  looks like there are no js folders in my subtheme?  would filename am i looking for?

**Comment by bassettsj** [comment]
You can add the file through the subtheme info file. [Learn more on Drupal.org](https://drupal.org/node/171205)

**Comment by swiders2** [comment]
awesome!  got it thanks.
