### ISSUE TITLE
Drush error

### ISSUE THREAD

**Issue by MetaBureau** [drupalprojects/kalatheme#60]
Kalatheme 7.x-3.0-rc3

"drush cc all" produces:

Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to undefined function theme_get_setting() in
/data/disk/o1/static/panopoly-7.x-1.6/sites/all/themes/kalatheme/includes/utils.inc,
line 304

**Comment by bassettsj** [comment]
Thanks for reporting that, please try updating to the 7.x-3.x-dev release. It has a fix for that issue. If that works go ahead and close this issue.

**Comment by pirog** [comment]
@bassettsj we should get a roadmap or milestone schedule for a 3.x-RC4 or 3.x-1.0 :)

**Comment by bassettsj** [comment]
3.0 is what we should aim for. I think we should do a round of testing on the current 3.0 branch and see what we can get taken care of to get this bad boy out the door. I think the only changes will be fixes, documentation and code quality. I would like to see the php files run thought PHP code sniffer to get the Drupal conventions taken care of. I also want to run the markup a bit through the HTML validator see if we are outputting missing tags or something.

**Comment by pirog** [comment]
if you are shooting for 3.x-1.0 then all that is what you should do

**Comment by MetaBureau** [comment]
not evident in dev thanks :)
