### ISSUE TITLE
Error in dev (June 24) after updating from 7.x-3.0-rc3

### ISSUE THREAD

**Issue by MetaBureau** [drupalprojects/kalatheme#63]
Fatal error: Call to undefined function kalatheme_lib_dir() in /data/disk/o1/static/panopoly-7.x-1.6/sites/all/themes/kalatheme/includes/utils.inc on line 337

**Comment by Krlos740** [comment]
I'm having the same error but in line 304

**Comment by pirog** [comment]
ick!

I'll look into this today!

**Comment by pirog** [comment]
are you guys using the latest dev?

**Comment by pirog** [comment]
Ok, i see this now. Should be fixed. Please reopen if not!
