### ISSUE TITLE
Responsive Toggling not working (7.x-3.0-rc3)

### ISSUE THREAD

**Issue by MetaBureau** [drupalprojects/kalatheme#64]
Latest stable Panels, testing using Desktop browser screen resize, Safari UA switching and with iPhone ...resposible toggling seems to have no effect when seeking to hide panel (Search API facet) from mobile.

**Comment by pirog** [comment]
@bassettsj probably have to do a similar fix here to what we did when fixing the style plugin

**Comment by pirog** [comment]
This should work now in latest dev. Please reopen if you have more problems!

**Comment by MetaBureau** [comment]
Thanks - tested okay :)
