### ISSUE TITLE
Bootstrap 3.2 update

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#65]
Update the bootstrap CDN versions to: 
`//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css`

**Comment by pirog** [comment]
@bassettsj im going through issues right now trying to set up a milestone for 3.0 release. There are some issues that have overlap ie maybe relevant to both 3.x and 4.x. We should probably have separate issues and just tag with major version? Does that sounds good or do you have a better suggestion?
