### ISSUE TITLE
Error generating subtheme in 4.x (Windows)

### ISSUE THREAD

**Issue by dariogcode** [drupalprojects/kalatheme#72]
I received the following error while trying to create a subtheme using 4.x version:

Warning: include_once(D:\www\client\project\code/D:\www\client\project\code\sites\all\themes\kalatheme\includes/../kalatheme.authorize.inc): failed to open stream: Invalid argument in _batch_finished() (line 461 of D:\www\client\project\code\includes\batch.inc).
Warning: include_once(): Failed opening 'D:\www\client\project\code/D:\www\client\project\code\sites\all\themes\kalatheme\includes/../kalatheme.authorize.inc' for inclusion (include_path='.;D:\xampp\php\PEAR') in _batch_finished() (line 461 of D:\www\client\project\code\includes\batch.inc).

The code in config.inc 

$file = dirname(**FILE**) . '/../kalatheme.authorize.inc';
$file = str_replace(DRUPAL_ROOT . '/', '', $file);

should use DIRECTORY_SEPARATOR

$file = dirname(**FILE**) . '/../kalatheme.authorize.inc';
$file = str_replace(DRUPAL_ROOT . DIRECTORY_SEPARATOR, '', $file);

**Comment by pirog** [comment]
@tilon does this fail in 3.x as well?

**Comment by pirog** [comment]
I've added this into 3.x, @tilon can you test it in 3.x and if it works can @bassettsj make sure it is in 4.x

**Comment by dariogcode** [comment]
@pirog I will try 3.x in Windows tomorrow and let you know.

**Comment by dariogcode** [comment]
@pirog, @bassettsj I can confirm Kalatheme 7.x-3.0-rc3+92-dev doesn't have this issue, subtheme is generated without errors.

**Comment by pirog** [comment]
@tilon awesome! 

@bassettsj let's def make sure this gets in 4.x then!

**Comment by pirog** [comment]
@bassettsj going to assume you merge the PR for this with master. reopen if needed.
@tilon will be in latest 4.x when its rebuilt from master.
