### ISSUE TITLE
kalatheme_lib_dir() rage!

### ISSUE THREAD

**Issue by labboy0276** [drupalprojects/kalatheme#73]
So this is happening now on Pantheon only

Warning: mkdir(): Permission denied in kalatheme_lib_dir() (line 345 of /srv/bindings/88bc69aeba2d4570a5229486c6e0d244/code/profiles/hotsauce/themes/kalatheme/includes/utils.inc)

On Install, also it gives a chmod error from the code I wrote before.

We will need to see what the right syntax is or how to make the directory and change the perms in something like pantheon

**Comment by katypool-zz** [comment]
Getting the same errors on pantheon: 

Warning: mkdir(): Permission denied in kalatheme_lib_dir() (line 345 of /srv/bindings/98feb60b74854cf88cd32ef8b6cc8fb3/code/sites/all/themes/kalatheme/includes/utils.inc).
Warning: chmod(): No such file or directory in kalatheme_lib_dir() (line 346 of /srv/bindings/98feb60b74854cf88cd32ef8b6cc8fb3/code/sites/all/themes/kalatheme/includes/utils.inc).

**Comment by pirog** [comment]
If you switch to SFTP mode on pantheon do these go away?

On Fri, Jun 27, 2014 at 5:19 PM, katypool notifications@github.com wrote:

> Getting the same errors on pantheon:
> 
> Warning: mkdir(): Permission denied in kalatheme_lib_dir() (line 345 of
> /srv/bindings/98feb60b74854cf88cd32ef8b6cc8fb3/code/sites/all/themes/kalatheme/includes/utils.inc).
> Warning: chmod(): No such file or directory in kalatheme_lib_dir() (line
> 346 of
> /srv/bindings/98feb60b74854cf88cd32ef8b6cc8fb3/code/sites/all/themes/kalatheme/includes/utils.inc).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/73#issuecomment-47412522
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by katypool-zz** [comment]
Yes they do

**Comment by labboy0276** [comment]
@pirog @katypool it seems that we be using not the latest version of kalatheme, the code that was there (that this error generates) is now gone.  As seen here:

https://github.com/drupalprojects/kalatheme/blob/7.x-3.x/includes/utils.inc

Even if we dont win with this codez, we can look into http://drupalcontrib.org/api/drupal/drupal%21includes%21file.inc/function/file_prepare_directory/7

**Comment by pirog** [comment]
pretty sure file_prepare_directory is what the libraries module uses so
that might be the ticket

On Sat, Jun 28, 2014 at 10:59 AM, John Ouellet notifications@github.com
wrote:

> @pirog https://github.com/pirog @katypool https://github.com/katypool
> it seems that we be using not the latest version of kalatheme, the code
> that was there (that this error generates) is now gone. As seen here:
> 
> https://github.com/drupalprojects/kalatheme/blob/7.x-3.x/includes/utils.inc
> 
> Even if we dont win with this codez, we can look into
> http://drupalcontrib.org/api/drupal/drupal%21includes%21file.inc/function/file_prepare_directory/7
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/73#issuecomment-47434203
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
we could also check if libraries is installed and just use the directory
create function they use

On Sat, Jun 28, 2014 at 11:51 AM, Mike Pirog mike@kalamuna.com wrote:

> pretty sure file_prepare_directory is what the libraries module uses so
> that might be the ticket
> 
> On Sat, Jun 28, 2014 at 10:59 AM, John Ouellet notifications@github.com
> wrote:
> 
> > @pirog https://github.com/pirog @katypool https://github.com/katypool
> > it seems that we be using not the latest version of kalatheme, the code
> > that was there (that this error generates) is now gone. As seen here:
> > 
> > https://github.com/drupalprojects/kalatheme/blob/7.x-3.x/includes/utils.inc
> > 
> > Even if we dont win with this codez, we can look into
> > http://drupalcontrib.org/api/drupal/drupal%21includes%21file.inc/function/file_prepare_directory/7
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/drupalprojects/kalatheme/issues/73#issuecomment-47434203
> > .
> 
> ## 
> 
> Cheers,
> 
> Mike Pirog
> Kalamuna
> www.kalamuna.com

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
you are correct, i looked at most contrib modules and that api function is used a few places.

**Comment by pirog** [comment]
@labboy0276 if GIT mode is enabled on pantheon you are just not going to have permission to create this dir on pantheon (and likely other things as well)... there may be an authorize.php implementation that solves the problem. 

I noticed that panopoly spins up with SFTP mode on by default instead of git, probably so it can install apps, so that is worth looking into also.

**Comment by pirog** [comment]
@labboy0276 there is an implementation in Kalatheme that uses the local file transfer protocol similar to teh apps module implementation that is probably your ticket to ride.

**Comment by pirog** [comment]
Ok. So

```
/**
 * Return the libraries dir to check
 */
function kalatheme_lib_dir() {
  if (!is_dir('sites/all/libraries')) {
    mkdir(DRUPAL_ROOT . '/sites/all/libraries');
    chmod(DRUPAL_ROOT . '/sites/all/libraries', 0755);
  } else {
    chmod(DRUPAL_ROOT . '/sites/all/libraries', 0755);
  }
  return is_dir('sites/all/libraries') ? 'sites/all/libraries' : 'sites/all';
}
```

The only point of this function is return the "location" of the libraries directory. Which may not exist yet if the user hasn't installed the libraries dir yet. It shouldn't try to create or change permissions on that dir at this point. It just wants to know where it is so another function can check if it is writable as part of a larger check to determine whether a user can upload a bootstrap library for their theme/subtheme or not.

```
/**
 * We want to check if the webserver can write our stuff to the right places.
 * If it can't then we are going to tell the user what's up.
 *
 * @return
 *   True if all good, message if no good
 */
function kalatheme_backend_check() {
  // Verify FTP support
  $ftp_installed = extension_loaded('ftp');
  // Verify SSH support
  $ssh_installed = extension_loaded('ssh2');
  // Verify web server write permissions
  $install_permissions = kalatheme_has_write_access();
  // Verify update module is enabled
  $updates_module = module_exists('update');

  return (($ftp_installed || $ssh_installed || $install_permissions) && $updates_module);
}

/**
 * Check whether Kalatheme has write access to libraries and modules directories.
 *
 * @return boolean
 */
function kalatheme_has_write_access() {
  return is_writable(drupal_realpath(kalatheme_lib_dir())) && is_writable(drupal_realpath('sites/all/modules'));
}
```

All this stuff is just to determine whether the user can actually write to that dir using one of many methods. It does not seek to actually try to write to it at this point. That stuff should happen when the user actually tries to upload a custom library or build a subtheme.

**Comment by pirog** [comment]
Aka this really should be something like this

```
/**
 * Return the libraries dir to check
 */
function kalatheme_lib_dir() {
  return is_dir('sites/all/libraries') ? 'sites/all/libraries' : 'sites/all';
}
```

**Comment by pirog** [comment]
OK. So, i've added a check to see if you are pantheon so the user is prompted to switch their connection mode to SFTP. 

As far as i understand things GIT mode will not currently allow us to create subthemes or install libraries on pantheon because drupal does not support a SFTP filetransfer protocol. this is the same result when you try to install a module or theme. @joshkoenig may have more insight here. 

I'm going to close this issue but if @katypool @labboy0276 and others can test on pantheon and reopen if applicable that would be great.

**Comment by MetaBureau** [comment]
I'm using Barracuda and had that issue but it now seems resolved.
