### ISSUE TITLE
Update font awesome and bootstrap for 3.0 release

### ISSUE THREAD

**Issue by pirog** [drupalprojects/kalatheme#78]
We want to upgrade to the latest bootstrap and font awesome for 3.x.

You might want to look at the following issues from 4.x to help.
https://github.com/drupalprojects/kalatheme/issues/65
https://github.com/drupalprojects/kalatheme/issues/45

**Comment by labboy0276** [comment]
@pirog I updated the CDN calls to the latest version on each.  It seems 4.x uses a who different approach with font-awesome.  Did you want that functionality in 3.x?

**Comment by pirog** [comment]
Do you mean 4.1x? We are already using 4.x for FA.

**Comment by labboy0276** [comment]
oh no i mean kalatheme 4.x

https://github.com/drupalprojects/kalatheme/pull/61

that whole grunt function

**Comment by pirog** [comment]
Got it. No i just wanted to update to the latest versions. Do they seem to cause any errors?

**Comment by labboy0276** [comment]
I tested locally with no problems, I will test other places and see, but it should be ok

**Comment by pirog** [comment]
yeah do a quick pass and then let me know. i would create a new subtheme
with FA and see if the thumbs up icon shows up in the status message that
says "looking good" or some such.

On Mon, Jun 30, 2014 at 10:26 AM, John Ouellet notifications@github.com
wrote:

> I tested locally with no problems, I will test other places and see, but
> it should be ok
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/78#issuecomment-47560113
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
All set I generated a site locally and one pantheon, tested the new font awesome 4.1 incon <i class="fa fa-bomb"></i> and it worked
