### ISSUE TITLE
7.x-3.0-rc3+84-dev - Warning: chmod(): Operation not permitted

### ISSUE THREAD

**Issue by MetaBureau** [drupalprojects/kalatheme#79]
Warning: chmod(): Operation not permitted in kalatheme_lib_dir() (line 348 of /data/disk/o1/static/panopoly-7.x-1.6/sites/all/themes/kalatheme/includes/utils.inc).

**Comment by pirog** [comment]
Best bet here is to just create sites/all/libraries and chmod it to 777

On Saturday, June 28, 2014, StewartMilne notifications@github.com wrote:

> Warning: chmod(): Operation not permitted in kalatheme_lib_dir() (line 348
> of
> /data/disk/o1/static/panopoly-7.x-1.6/sites/all/themes/kalatheme/includes/utils.inc).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/79.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by MetaBureau** [comment]
Is this related to sub-theme generation? My opinion is that sub-theme tasks are easily achieved with drush or manually ... so if up to me wouldn't be worrying about providing a UI for this (adds risk, distraction from more important things).

**Comment by pirog** [comment]
Not necessarily although it can be.

UI is important. One of the goals of kalatheme is ease of use for novices.
http://www.kalamuna.com/news/power-people
May give a better sense of where we are coming from

On Saturday, June 28, 2014, StewartMilne notifications@github.com wrote:

> Is this related to sub-theme generation? My opinion is that sub-theme
> tasks are easily achieved with drush or manually ... so if up to me
> wouldn't be worrying about providing a UI for this (adds risk, distraction
> from more important things).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/79#issuecomment-47446910
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by MetaBureau** [comment]
Yep ... just been reading up on it all now. Testing out KalaBox ... Very Nice :)

**Comment by pirog** [comment]
That said... There is still work to be done on both! Adventures in open
source :) sigh

On Saturday, June 28, 2014, StewartMilne notifications@github.com wrote:

> Yep ... just been reading up on it all now. Testing out KalaBox ... Very
> Nice :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/79#issuecomment-47447043
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
@MetaBureau this should be in the latest dev of 3.x see:
https://github.com/drupalprojects/kalatheme/issues/73

**Comment by MetaBureau** [comment]
I'm using Barracuda and had that issue but it now seems resolved - no error - but the sub-theme is not generated. I haven't changed permissions on sites/all/libraries as Barracuda manages permissions.
