### ISSUE TITLE
7.x-3.0-rc3+74-dev Can't disable any user role permissions

### ISSUE THREAD

**Issue by ashtronaut** [drupalprojects/kalatheme#80]
When Kalatheme or a custom sub-theme is set as my administration theme, I cannot disable any permissions on the admin/people/permissions page.  I can however, enable the permissions with no problems

This is exactly what is happening. . . 
Once the permission is unchecked, I push the "Save Permissions" button and the page reloads and reads "The changes have been saved.", but the permission is still checked and enabled.  

The only way to disable the permission is to switch to any other admin theme that is not Kalatheme or a sub-theme and repeat the process. 

I can enable any permission without any problems.

I am running Panopoly-7.x-1.6 on a shared bluehost instance.  There are no strange log messages showing.

Please Advise.  
ash

**Comment by pirog** [comment]
Very interesting. I've actually experienced this before but never thought it was kalatheme. Let me look into it and ill let you know.

**Comment by pirog** [comment]
Yup. This definitely seems to be happening!

**Comment by ashtronaut** [comment]
In my research of the problem I came across the following post in the Panopoly Issues queue.  Maybe it will help. . . .  

https://www.drupal.org/node/2272977

Is it possible that either Kalatheme handles checkboxes the same way as the Radix base-theme?  Maybe an issue with Bootstrap?

**Comment by pirog** [comment]
It's likely this is the same. Radix and Kalatheme borrow a decent amount of stuff from one another.

**Comment by ashtronaut** [comment]
Here is a link to the patches for Radix.  

https://www.drupal.org/node/2206229

Hope it helps.  I would try to help, but my skills are not quite up to par. . . .

**Comment by pirog** [comment]
@andrewmallis i think this is what was responsible for our inability to change perms on BKS

**Comment by pirog** [comment]
@ashtronaut try the latest dev and reopen if that does not resolve your issue

**Comment by ashtronaut** [comment]
pulled down latest dev, disabled kalatheme & sub-theme, uploaded & extracted latest dev & re-enabled  Still showing same behavior as before.  Do I need to build a new sub-theme?

**Comment by pirog** [comment]
where are you "pulling" it down from?

On Sun, Jun 29, 2014 at 2:27 PM, Ash notifications@github.com wrote:

> pulled down latest dev, disabled kalatheme & sub-theme, uploaded &
> extracted latest dev & re-enabled Still showing same behavior as before. Do
> I need to build a new sub-theme?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/80#issuecomment-47476106
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by ashtronaut** [comment]
http://ftp.drupal.org/files/projects/kalatheme-7.x-3.x-dev.tar.gz

had today's date so I figured it was all good

**Comment by pirog** [comment]
I'm guessing its actually from really early morning. Will probably need to wait until they
 generate it again or just pull down the latest code from github or d.o with git.

**Comment by pirog** [comment]
Actually that should have the commit in it. Maybe you need a cache clear?

**Comment by ashtronaut** [comment]
Downloaded from git and it worked like a charm!  Thank you sir!
