### ISSUE TITLE
Update Kalatheme documentation on D.o

### ISSUE THREAD

**Issue by pirog** [drupalprojects/kalatheme#81]
This documentation is out of date and needs to be brought up to speed to reflect the latest 3.x. Please keep in mind that 4.x documentation will be happening at some point as well.

Here are the current docs 
https://www.drupal.org/node/1949678

@katypool, do you think this is something you would be interested in updating?

**Comment by pirog** [comment]
You may want to also consider posting the docs on d.o in the wiki here on github as well.

**Comment by katypool-zz** [comment]
I can definitely work on this!

**Comment by pirog** [comment]
Awesome!

I would just go through the current docs page by page and change them to reflect how the latest 3.x dev works. High level goals are for the copy to be light and humorous but informative, good images to show what is going down and as concise as possible. This will be a great opportunity for you to really explore the dark depths of Kalatheme as well.

Ping me here or IRL if you need any help or guidance.

**Comment by pirog** [comment]
Also i totally just used IRL. Win.

**Comment by katypool-zz** [comment]
@pirog Soooo I've gone through all the documentation on d.o. and could use some guidance on what needs to be updated. Was the current documentation written for the 1.x branch?

**Comment by pirog** [comment]
@katypool i am not EXACTLY sure what needs to be updated :) 

What i would do is systematically go through the current docs and try all the things out. For sections where the docs dont reflect what things look like in 3.x-dev just ping me here and i'll tell you where to look. For example i am 100% sure that the "subtheme generator" exists at a different location now. 

Alternately, if you want we can meet for like 30 minutes or so on Thursday and go over all the sections together and put a plan together for all the pages. Maybe that sounds better?

**Comment by bassettsj** [comment]
- [ ] Remove references to the kalatheme_sass repo
- [ ] Add documentation on how to use kalatheme without using `libraries`
- [ ] Documentation for how to use the master source

**Comment by pirog** [comment]
Good additions! might want to leave some of the more complicated docs ie building from master source to you @bassettsj unless @katypool is up for a challenge of course :)

**Comment by katypool-zz** [comment]
all right, thanks guys! For now I'll look out for the kalatheme_sass references since that seems pretty easy to tackle. And then @pirog if we could meet for a few mins Thursday that would be helpful

**Comment by pirog** [comment]
Let's do that! I'll send you an invite!

On Tue, Jul 1, 2014 at 4:41 PM, katypool notifications@github.com wrote:

> all right, thanks guys! For now I'll look out for the kalatheme_sass
> references since that seems pretty easy to tackle. And then @pirog
> https://github.com/pirog if we could meet for a few mins Thursday that
> would be helpful
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/81#issuecomment-47722027
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by bassettsj** [comment]
@katypool I would first make the changes in the [README](https://github.com/drupalprojects/kalatheme/blob/master/README.md) and the [CONTRIBTUE](https://github.com/drupalprojects/kalatheme/blob/master/CONTRIBUTING.md) first. If you fork the repo, submit the changes there. Then we can use that as html for D.O documentation.

**Comment by bassettsj** [comment]
@pirog Send me an invite too porfavor!

**Comment by pirog** [comment]
SENT! Didn't want to bug you with the meeting but def happy to have you
there!

On Tue, Jul 1, 2014 at 4:43 PM, Steven Bassett notifications@github.com
wrote:

> @pirog https://github.com/pirog Send me an invite too porfavor!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/81#issuecomment-47722117
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by katypool-zz** [comment]
@pirog @bassettsj A wild wiki appears!
https://github.com/katypool/kalatheme/wiki

**Comment by reynoldsalec** [comment]
Party, @katypool can deploy this into the main Kalatheme project wiki.

@pirog will link from the D.o. documentation to the Kalatheme wiki.

**Comment by katypool-zz** [comment]
Wiki is now live! Unfortunately I find myself in possession of no golden spike. 
We actually still need a SASS page, which is linked to on some of the other pages. I think @bassettsj wanted to handle that (other pages link to a blank wiki/SASS-with-Kalatheme page, so if you just edit that page I won't have to go through and fix any links within the existing documentation)

**Comment by pirog** [comment]
@katypool @reynoldsalec i've linked the docs in D.o but i can't really remove the child pages. So if someone finds the current kalatheme docs on D.o which they would by googling "kalatheme docs" they can see all the old child pages. Any thoughts on what to do here?

Any ideas on what to do thatee

**Comment by katypool-zz** [comment]
I can go through and link to the wiki on each child page on d.o. (and delete the old documentation on those pages?)

**Comment by pirog** [comment]
I don't know if you can delete those children pages but i think that would be ideal. Either way we need to make sure that people know... and are directed to the new docs. 

@katypool do whatever you think is best to achieve this and let me know if you need anything!

**Comment by katypool-zz** [comment]
this issue can be closed!

**Comment by pirog** [comment]
Hooray!
