### ISSUE TITLE
Make sure relevant fixes from 3.0 are in master/4.x

### ISSUE THREAD

**Issue by pirog** [drupalprojects/kalatheme#85]
There are some things we are going to want to move forward to master/4.x. This is a good list of differences that we might want to include.
https://github.com/drupalprojects/kalatheme/compare/master...7.x-3.x

**Comment by pirog** [comment]
Submitted PR's for everything in list about except:
1. #63 #64 #46 are already there
2. #76 should be handled in SCSS by @bassettsj 
3. #78 should be in already

Only real actionable thing here @bassettsj  is to make sure #76 gets in wherever its supposed. After that i think we can merge the PRs and then close this out.

**Comment by andrewmallis** [comment]
4.x will take a new direction. This task is no longer required
