### ISSUE TITLE
Hastings layout not available after fresh install of Kalatheme subtheme?

### ISSUE THREAD

**Issue by parijke** [drupalprojects/kalatheme#89]
I see a couple of issues in drupal.org discussing the overriding of the panopoly layouts. One of them speaks of the hastings layout.

In my fresh installation of kalatheme subtheme, I can't see any Hastings layout, so I am wondering if I missed a step?

**Comment by pirog** [comment]
We removed those layouts in 3.x :(

On Mon, Jun 30, 2014 at 5:59 PM, parijke notifications@github.com wrote:

> I see a couple of issues in drupal.org discussing the overriding of the
> panopoly layouts. One of them speaks of the hastings layout.
> 
> In my fresh installation of kalatheme subtheme, I can't see any Hastings
> layout, so I am wondering if I missed a step?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/issues/89.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by parijke** [comment]
Aha okee, I am not missing anything.... btw, why?

**Comment by pirog** [comment]
Thought they were excessive. It's not great to load layouts in a theme. We also were planning to add in a easy responsive layout builder powered by the IPE but that has gotten sidelined for a bit.
