### ISSUE TITLE
What do we need to get 7.x-3.0 out the door

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#9]
@pirog I want to start getting 7.x-4.x out soonish. What do you think we should tighten up on the 7.x-3.x branch so we can start really getting onto 7.x-4.x ready.

**Comment by pirog** [comment]
the only things i need to do on the 3.x branch are related to the hotsauce install profile workflow. i think you can still proceed on 4.x with gusto and i can merge the more backend related stuff i still need to do on 3.x as i go.

**Comment by pirog** [comment]
i would honestly would not worry a lot about 3.x ... i just needed to branch because we need to get hotsauce working but 4.x isn't ready to ship yet so i needed someplace to put commits in front of a stable release but still behind you

**Comment by bassettsj** [comment]
I don't think you should add any new backend features to 3.x but any minor improvements and fixes are good. Is there anything I should do for 3.x to get it out soon?—

**Comment by pirog** [comment]
no new features... mostly just bug fixes to get kalatheme to play nice with the hotsauce installer.

**Comment by bassettsj** [comment]
That sounds perfect. I am so psyched to work on this project. I think we're going to have a kickass base theme that is easy to use. —

**Comment by pirog** [comment]
me too. its going to be really awesome! i can't wait for 4.x and the generator to be ready... that is when things are going to get really spicy.

**Comment by bassettsj** [comment]
Can we call the generator 'sauce'?—

**Comment by pirog** [comment]
Is the planck length 1.61619926 × 10-35 meters?
